name: Test Coverage

on: push

jobs:
  build:
    name: Build and Test Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Server
        run: npm ci

      - name: Create env.test file
        run: |
          touch .env.test
          echo JWT_SECRET="${{ vars.JWT_SECRET }}" > .env.test
          echo BEARER_TOKEN="${{ vars.BEARER_TOKEN }}" > .env.test
          echo BEARER_TOKEN_WRONG_EMAIL="${{ vars.BEARER_TOKEN_WRONG_EMAIL }}" > .env.test
          cat .env

      - name: Run Test Coverage
        run: npm run test