name: Test Coverage

on: push

jobs:
  build:
    name: Build and Test Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Server
        run: npm ci

      - name: Run Test Coverage
        run: npm run test